version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    groups:
      androidx-test:
        patterns:
          - "androidx.test*"
      androidx:
        patterns:
          - "androidx.*"
      kotlin:
        patterns:
          - "org.jetbrains.kotlin*"
          - "com.google.devtools.ksp*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
