[versions]
androidGradlePlugin = "8.10.0"
kotlin = "2.1.20"

coreKtx = "1.16.0"
lifecycle = "2.9.0"
activityCompose = "1.10.1"
composeBom = "2025.05.00"
dataStore = "1.1.6"
circuit = "0.27.1"
hilt = "2.56.2"

licensee = "1.13.0"
ktlint = "1.3.1"
ktlintGradle = "12.1.1"

ktor = "3.1.3"
retrofit = "2.11.0"

roborazzi = "1.43.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version = "2.9.0" }
androidx-hilt-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version = "1.2.0" }

androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }

androidx-datastore = { group = "androidx.datastore", name = "datastore", version.ref = "dataStore" }
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "dataStore" }

tink-android = { group = "com.google.crypto.tink", name = "tink-android", version = "1.17.0" }

circuit-foundation = { group = "com.slack.circuit", name = "circuit-foundation", version.ref = "circuit" }
circuit-test = { group = "com.slack.circuit", name = "circuit-test", version.ref = "circuit" }

hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }

ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }
ktor-client-mock = { group = "io.ktor", name = "ktor-client-mock", version.ref = "ktor" }
ktor-server-jetty = { group = "io.ktor", name = "ktor-server-jetty-jakarta", version.ref = "ktor" }
ktor-server-core = { group = "io.ktor", name = "ktor-server-core", version.ref = "ktor" }
ktor-network-tls = { group = "io.ktor", name = "ktor-network-tls-certificates", version.ref = "ktor" }

kotlinx-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version = "1.8.1" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version = "1.10.2" }

okhttp-bom = { group = "com.squareup.okhttp3", name = "okhttp-bom", version = "4.12.0" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp" }
okhttp-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit" }
moshi-kotlin = { group = "com.squareup.moshi", name = "moshi-kotlin", version = "1.15.2" }

# test frameworks
junit = { group = "junit", name = "junit", version = "4.13.2" }
kotest-assertions-core = { group = "io.kotest", name = "kotest-assertions-core", version = "5.9.1" }
robolectric = { group = "org.robolectric", name = "robolectric", version = "4.14.1" }
androidx-test-runner = { group = "androidx.test", name = "runner", version = "1.6.2" }
androidx-test-rules = { group = "androidx.test", name = "rules", version = "1.6.1" }
androidx-test-core-ktx = { group = "androidx.test", name = "core-ktx", version = "1.6.1" }
androidx-test-ext-junit-ktx = { group = "androidx.test.ext", name = "junit-ktx", version = "1.2.1" }
composable-preview-scanner = { group = "io.github.sergio-sastre.ComposablePreviewScanner", name = "android", version = "0.6.1" }
roborazzi-compose-preview = { group = "io.github.takahirom.roborazzi", name = "roborazzi-compose-preview-scanner-support", version.ref = "roborazzi" }

# import for build-logic
android-gradle-plugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
licensee-gradle-plugin = { group = "app.cash.licensee", name = "licensee-gradle-plugin", version.ref = "licensee" }
ktlint-gradle-plugin = { group = "org.jlleitschuh.gradle", name = "ktlint-gradle", version.ref = "ktlintGradle" }
roborazzi-gradle-plugin = { group = "io.github.takahirom.roborazzi", name = "roborazzi-gradle-plugin", version.ref = "roborazzi" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
maven-publish = { id = "com.vanniktech.maven.publish", version = "0.31.0" }

kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version = "2.1.20-2.0.1" }

ktlint-gradle = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintGradle" }
licensee = { id = "app.cash.licensee", version.ref = "licensee" }

roborazzi = { id = "io.github.takahirom.roborazzi", version.ref = "roborazzi" }

cybozux-authentication-android-application = { id = "com.cybozux.authentication.android.application" }
cybozux-authentication-android-library = { id = "com.cybozux.authentication.android.library" }
cybozux-authentication-pure-android-library = { id = "com.cybozux.authentication.pure.android.library" }
cybozux-authentication-kotlin-library = { id = "com.cybozux.authentication.kotlin.library" }
cybozux-authentication-screenshot-test = { id = "com.cybozux.authentication.screenshot.test" }
cybozux-authentication-maven-publish = { id = "cybozux.authentication.maven.publish" }

[bundles]
robolectric-junit-test = [
    "robolectric",
    "androidx-core-ktx",
    "androidx-test-ext-junit-ktx",
]
android-instrumented-test = [
    "junit",
    "androidx-test-runner",
    "androidx-test-rules",
    "androidx-test-core-ktx",
    "androidx-test-ext-junit-ktx"
]
