name: 'Setup Java'
description: 'Setup Java with specified version'

runs:
  using: 'composite'
  steps:
    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '21'
