name: Check

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  ORG_GRADLE_PROJECT_warningsAsErrors: true

jobs:
  local_test:
    name: Local Test
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-java
      - uses: gradle/actions/setup-gradle@v4

      - name: Run lint
        run: ./gradlew lint ktlintCheck

      - name: Check license
        run: ./gradlew licensee

      - name: Run local tests
        run: ./gradlew testDebugUnitTest

      - name: Build sample app
        run: ./gradlew :sample-app:assembleDebug

      - name: Upload check results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: local-test-reports
          retention-days: 30
          path: |
            ./**/build/reports/lint-results-*.html
            ./**/build/reports/tests

  instrumented_test:
    name: Instrumented Test
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        include:
          - api-level: 27
            target: default
          - api-level: 35
            target: aosp_atd

    steps:
      - name: Delete unnecessary tools
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1
        with:
          android: false # Don't remove Android tools
          tool-cache: true
          dotnet: true
          haskell: true
          swap-storage: true
          docker-images: false # Takes 16s, enable if needed in the future
          large-packages: false # includes google-cloud-sdk and it's slow

      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-java
      - uses: gradle/actions/setup-gradle@v4

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: AVD cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}-${{ matrix.target }}

      - name: Create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@1dcd0090116d15e7c562f8db72807de5e036a4ed # v2.34.0
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          target: ${{ matrix.target }}
          disk-size: 6000M
          ram-size: 2048M
          heap-size: 600M
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Run android tests
        uses: reactivecircus/android-emulator-runner@1dcd0090116d15e7c562f8db72807de5e036a4ed # v2.34.0
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          target: ${{ matrix.target }}
          disk-size: 6000M
          ram-size: 2048M
          heap-size: 600M
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew connectedDebugAndroidTest

      - name: Upload check results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: instrumented-test-reports-api-${{ matrix.api-level }}
          retention-days: 30
          path: |
            ./**/build/reports/androidTests
