name: Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**/.gitignore'
      - '**/.editorconfig'
      - 'docs/**'

jobs:
  deploy-modules:
    name: Deploy to GitHub Packages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-java
      - uses: gradle/actions/setup-gradle@v4

      - name: Publish to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew publishAllPublicationsToGitHubPackagesRepository
