name: Update Gradle Wrapper

on:
  workflow_dispatch:
  schedule:
    # Every Sunday at 18:00 UTC
    # Every Monday at 3:00 JST
    - cron: '0 18 * * 0'

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-java
      - uses: gradle/actions/setup-gradle@v5

      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@512b1875f3b6270828abfe77b247d5895a2da1e5 # v2.1.0
        with:
          labels: dependencies # gradle-wrapper label will also be added automatically
          merge-method: MERGE
